defmodule Shep.AgentRunner.PR do
  @moduledoc """
  Push and pull-request creation for a finished task: push the branch,
  open the PR against the staging target, and best-effort label it. A
  missing label in the target repo never sinks the PR.
  """

  require Logger

  @doc "Push a branch to origin. Returns `:ok` or `{:error, output}`."
  @spec push_branch(Shep.Task.t(), String.t()) :: :ok | {:error, String.t()}
  def push_branch(task, cwd) do
    case System.cmd("git", ["push", "origin", task.branch], cd: cwd, stderr_to_stdout: true) do
      {_, 0} -> :ok
      {err, _} -> {:error, err}
    end
  end

  @doc """
  Create a PR for a completed task, pushing its branch first. Returns
  `{:ok, url}`, `:none` (demo tasks, uncommitted changes, or a non-Complete
  completion), or `{:error, reason}`.
  """
  @spec create(struct(), Shep.Task.t(), String.t(), map()) ::
          {:ok, String.t()} | :none | {:error, String.t()}
  def create(_completion, %{demo: true} = task, _path, _config) do
    Logger.info("Demo task #{task.id}: skipping push and PR creation")
    :none
  end

  def create(%Shep.Completion.Complete{summary: summary}, task, worktree_path, config) do
    if Shep.Worktree.has_uncommitted_changes?(worktree_path) do
      Logger.warning("Worktree has uncommitted changes, skipping PR")
      :none
    else
      push_and_pr(task, summary, config, worktree_path)
    end
  end

  def create(_completion, _task, _path, _config), do: :none

  defp push_and_pr(task, summary, config, cwd) do
    repo = get_in(config, ["tracker", "repo"])
    target = get_in(config, ["staging", "pr_target"]) || task.base_branch

    case push_branch(task, cwd) do
      :ok ->
        label =
          if task.no_merge,
            do: "shep:no-merge",
            else: "agent: claude-code"

        pr_args = [
          "pr",
          "create",
          "--repo",
          repo,
          "--base",
          target,
          "--head",
          task.branch,
          "--title",
          "[Shep] #{task.id}: #{String.slice(summary, 0, 60)}",
          "--body",
          "## Summary\n\n#{summary}\n\n---\nGenerated by Shep (task #{task.id})"
        ]

        case Shep.GH.run(pr_args) do
          {:ok, url} ->
            Logger.info("PR created: #{url}")
            apply_pr_label(repo, url, label)
            Shep.Tracker.update_status(task.id, "pr-created")
            {:ok, url}

          {:error, err} ->
            {:error, "PR creation failed: #{err}"}
        end

      {:error, err} ->
        {:error, "push failed: #{err}"}
    end
  end

  # Best-effort: a missing label in the target repo must never sink the PR.
  defp apply_pr_label(repo, pr_url, label) do
    case Shep.GH.run(["pr", "edit", pr_url, "--repo", repo, "--add-label", label]) do
      {:ok, _} -> :ok
      {:error, err} -> Logger.warning("Could not label PR (#{label}): #{err}")
    end
  end
end
