defmodule Shep.Demo do
  @moduledoc """
  Scaffolding for `mix shep.demo`.

  The demo needs a workflow config (memory tracker, stub agent) and a
  stub agent script. Both are generated into a temp dir at runtime so
  nothing demo-shaped ships as a package asset, and the demo works on
  a machine with no agent CLI and no git identity.
  """

  @stub_agent ~S"""
  #!/bin/sh
  # Stub agent generated by `mix shep.demo`. Stands in for a real coding
  # agent so the full orchestration loop (worktree, dispatch, streaming,
  # completion) can be seen without an agent CLI, labels, or a target repo.
  set -eu

  for line in \
    "Reading the briefing..." \
    "Inspecting the worktree..." \
    "Making the change (pretend furiously typing)..." \
    "Running the checks..." \
    "All green. Wrapping up."
  do
    echo "$line"
    sleep 0.4
  done

  # make a real, minimal change so the branch has a diff worth a PR
  echo "🐑 Grazed by Shep on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> PASTURE.md
  git add PASTURE.md
  # -c identity: the demo must commit even on machines with no git identity
  git -c user.name='Shep Demo' -c user.email='demo@shep.invalid' \
    commit -q -m "chore: let Shep graze in PASTURE.md"
  echo "Committed PASTURE.md."

  echo '<completion>{"type": "complete", "summary": "Grazed PASTURE.md and committed the change.", "verify": ["orchestrator dispatched into an isolated worktree", "stdout streamed line-buffered", "a real commit landed on the task branch", "completion signal parsed"]}</completion>'
  """

  @doc """
  Write the demo workflow and stub agent into a fresh temp dir.
  Returns `%{dir: dir, workflow: path, agent: path}`.
  """
  @spec scaffold() :: %{dir: String.t(), workflow: String.t(), agent: String.t()}
  def scaffold do
    dir = Path.join(System.tmp_dir!(), "shep_demo_#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)

    agent = Path.join(dir, "stub_agent.sh")
    File.write!(agent, @stub_agent)
    File.chmod!(agent, 0o755)

    workflow = Path.join(dir, "WORKFLOW.md")
    File.write!(workflow, workflow_md(agent))

    %{dir: dir, workflow: workflow, agent: agent}
  end

  @doc "Remove a scaffold created by `scaffold/0`."
  @spec cleanup(%{dir: String.t()}) :: :ok
  def cleanup(%{dir: dir}) do
    File.rm_rf!(dir)
    :ok
  end

  defp workflow_md(agent_path) do
    """
    ---
    tracker:
      kind: "memory"

    polling:
      interval_ms: 3600000

    workspace:
      root: .shep/demo_worktrees

    agent:
      command: "#{agent_path}"
      max_concurrent: 1
      max_turns: 1
      idle_timeout_ms: 60000
      total_timeout_ms: 120000

    hooks:
      hook_timeout_ms: 10000

    staging:
      base_branch: "main"
      pr_target: "main"
    ---

    # Shep Demo Workflow

    Generated by `mix shep.demo`: memory tracker, stub agent, no PR creation.
    """
  end
end
